### ISSUE TITLE
Процедура Журнал_Добавить

### ISSUE THREAD

**Issue by laskin82** [mevgenym/1c_vetis.api#10]
Добрый день.

Код не соответствует структуре метаданных. Полей представление и Объект нет в исходной версии.
```
МенеджерЗаписи = РегистрыСведений.ВетисЖурнал.СоздатьМенеджерЗаписи();
МенеджерЗаписи.Период        = ТекущаяДата();
МенеджерЗаписи.Миллисекунды  = Период % 1000;
**МенеджерЗаписи.Представление = Лев(пТекст, 100);**
МенеджерЗаписи.Хранилище     = Новый ХранилищеЗначения(пТекст, Новый СжатиеДанных(9));
МенеджерЗаписи.Пользователь  = Пользователи.ТекущийПользователь();
МенеджерЗаписи.Версия        = Версия();
**МенеджерЗаписи.Объект        = пОбъект;**

```

**МенеджерЗаписи.Представление**
**МенеджерЗаписи.Объект**

**Comment by VladimirVS89** [comment]
Процедура Журнал_Добавить(пТекст, пОперация = Неопределено, пОбъект = Неопределено) Экспорт
	
	Период = ТекущаяУниверсальнаяДатаВМиллисекундах();
	
	МенеджерЗаписи = РегистрыСведений.ВетисЖурнал.СоздатьМенеджерЗаписи();
	МенеджерЗаписи.Период        = ТекущаяДата();
	МенеджерЗаписи.Миллисекунды  = Период % 1000;
	МенеджерЗаписи.Расшифровка   = Лев(пТекст, 100);
	МенеджерЗаписи.Хранилище     = Новый ХранилищеЗначения(пТекст, Новый СжатиеДанных(9));
	МенеджерЗаписи.Пользователь  = Пользователи.ТекущийПользователь();
	МенеджерЗаписи.Версия        = Версия();

	
	Если ТипЗнч(пОперация) = Тип("Строка") Тогда
		МенеджерЗаписи.Контекст      = пОперация;
	Иначе
		МенеджерЗаписи.КлючДанных    = пОперация;
	КонецЕсли;
	
	МенеджерЗаписи.Записать();
	
КонецПроцедуры

**Comment by laskin82** [comment]
оформить в виде пул реквеста?

**Comment by mevgenym** [comment]
Может быть у вас устаревшая версия кода, возможно из-за того что cf обновляется реже текстов.
https://github.com/mevgenym/1c_vetis.api/blob/fd398c26289eec5528bd1f8a9d6138f0bafaacd9/src/CommonModule.%D0%92%D0%B5%D1%82%D0%B8%D1%81.Module.txt#L474-L495

**Comment by laskin82** [comment]
По вашей ссылке код старый. Я беру код не из cf, а из src

**Comment by mevgenym** [comment]
да увидел, последний коммит был неполный
