### ISSUE TITLE
ошибки десериализации не обрабатываются

### ISSUE THREAD

**Issue by jafariuse** [mevgenym/1c_vetis.api#2]
При десериализации пакета, могут встречаться данные, не соответствующие фасету. В результате дропается весь пакет. i.e.

> Значение: 'Транспортировка при температуре от 0 до +6С. Разрешение на вывоз №30/1981 от 06.04.2017г., выдано Республиканской Ветслужбой РМ. Мониторинговые исслед. сырья экспер.№23891-23940.В от 17.03.2017г. метод ПЦР в пробах генетич.мат-л вируса АЧС не выделен. Лаборатория ГБУ "Мордовская РВЛ" Компартмент 4.' не соответствует простому типу: {http://api.vetrf.ru/schema/cdm/base}String255
> Несоответствие фасету MaxLength = '255'

Хотелось иметь возможность насильно привести к типу или дропнуть только это значение.

**Comment by mevgenym** [comment]
Я думаю, такие ошибки лучше решать через тех. поддержку Меркурия. Насильно привести к типу это взять значение свойства ОбъектXDTO до десериализации. И, как вариант, изменить схему xsd и пользоваться своей. Может есть еще вариант, предлагайте.

**Comment by jafariuse** [comment]
> Я думаю, такие ошибки лучше решать через тех. поддержку Меркурия
Это в идеальной ситуации, а надо, как правило, здесь и сейчас.

> изменить схему xsd и пользоваться своей
Не самое лучшее решение. Потом по этой схеме еще ответ делать, а он с той стороны валидацию не пройдет. 

предлагаю примерно так: 
```
Если ТипЗнч(_Чтение) = Тип("СписокXDTO") тогда 
	Попытка
		Результат = пФабрика.ПрочитатьXML(_Чтение, пТип);
	Исключение
		Результат = новый списокЗначений;
		для каждого ОбъектXD из _Чтение цикл 
			Попытка
				результат.добавить(пФабрика.ПрочитатьXML(ОбъектXD, пТип);
			Исключение 
			КонецПопытки;
		КонецЦикла;
	КонецПопытки;
Иначе
	Результат = пФабрика.ПрочитатьXML(_Чтение, пТип);
КонецЕсли;

```
т.о. Если из получаемых объектов один не прочитается - есть шанс прочитать остальные. 

Если все совсем плохо - использую вот такую функцию:
```
Функция ВыгрузитьОбъектВструктуру(ОбъектXDTO)Экспорт 
	Структура = новый Структура();
	для каждого Свойство из ОбъектXDTO.свойства() цикл 
		//списочноеСвойство получаться не хочет. будем идти через строку
		//ЗначениеСвойства = ОбъектXDTO.получить(Свойство);
		ЗначениеСвойства = Вычислить("ОбъектXDTO."+Свойство);
		
			если ТипЗнч(ЗначениеСвойства) = тип("ОбъектXDTO") тогда
				значение = ВыгрузитьОбъектВструктуру(ЗначениеСвойства);
			ИначеЕсли ТипЗнч(ЗначениеСвойства) = тип("СписокXDTO") тогда
				значение = новый Массив;
				для каждого элемента из ЗначениеСвойства цикл 
					Если ТипЗнч(элемента) = тип("ОбъектXDTO") или ТипЗнч(элемента) = тип("СписокXDTO") тогда
						значение.Добавить(ВыгрузитьОбъектВструктуру(элемента));
					иначе
						значение.Добавить(СериализаторXDTO.XMLЗначение(ТипЗнч(элемента), элемента));
					КонецЕсли;
				КонецЦикла;
			иначе
				значение = ЗначениеСвойства;
			КонецЕсли;
			Структура.Вставить(Свойство.Имя, Значение);
	КонецЦикла;
	возврат Структура;
КонецФункции
```

Таким образом разбираются данные в самых запущенных случаях 

З.Ы. Естественно, все эти девиации нужны только в переходном периоде, пока не отработаются механизмы в самом Меркурии

**Comment by mevgenym** [comment]
добавил обработку
