### ISSUE TITLE
Функция EnterpriseList при работе с API 1.4

### ISSUE THREAD

**Issue by malikov-pro** [mevgenym/1c_vetis.api#8]
В общем модуле "ВетисCerberusEnterprise", в "Функция EnterpriseList" идет присваивание строкового значения "enterpriseGuid", хотя тип EnterpriseList состоит из объектов типа "Enterprise".

Ошибка при работе
"Несоответствие типов XDTO:
Тип '{http://api.vetrf.ru/schema/cdm/cerberus/enterprise}Enterprise' не найден
Значение не может быть установлено свойству, имеющему объектный тип"

Запускал из РегистрСведений.ВетисПредприятияХС.Форма.ФормаСписка.Форма.КомандаПривязатьВСервисе

**Comment by malikov-pro** [comment]
в ОбщийМодуль.ВетисCerberusEnterprise, функция "BusinessEntityActivityLocationsModificationOperation"

ВетисОбщегоНазначения.УстановитьЗначение(_Объект, EnterpriseList(enterpriseGuid), "enterpriseList");

изменить на 

Enterprise = Enterprise(enterpriseGuid);
ВетисОбщегоНазначения.УстановитьЗначение(_Объект, EnterpriseList(Enterprise), "enterpriseList");

после работает нормально

**Comment by mevgenym** [comment]
Поправил. Спасибо!
